# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "PopGames"
client_id = "8264fe948822caff6f49c871198a559a"
application_url = "https://pop-games.fly.dev"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_discounts,write_customers,read_customers,read_orders"

[auth]
redirect_urls = [
  "https://pop-games.fly.dev/auth/callback",
  "https://pop-games.fly.dev/auth/shopify/callback",
  "https://pop-games.fly.dev/api/auth/callback",
  "https://pop-games.fly.dev/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[app_proxy]
url = "https://pop-games.fly.dev/popup"
subpath = "handle-pop-up"
prefix = "apps"

[pos]
embedded = false
