# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "pop-games"
client_id = "8264fe948822caff6f49c871198a559a"
application_url = "https://06c3-216-196-164-185.ngrok-free.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://06c3-216-196-164-185.ngrok-free.app/auth/callback",
  "https://06c3-216-196-164-185.ngrok-free.app/auth/shopify/callback",
  "https://06c3-216-196-164-185.ngrok-free.app/api/auth/callback",
  "https://06c3-216-196-164-185.ngrok-free.app/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-9f306b3f.myshopify.com"
